version: "3"
services:
  web:
    image: node:latest
    container_name: express-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: npm start
